Fix converting from initializer list would use explicit constructor
```
../../net/dns/host_cache.cc: In constructor ‘net::HostCache::Entry::Entry(std::vector<std::unique_ptr<net::HostResolverInterna
lResult> >, base::Time, base::TimeTicks)’:
../../net/dns/host_cache.cc:392:40: error: converting to ‘absl::optional<std::vector<bool> >’ from initializer list would use explicit constructor ‘constexpr absl::optional<T>::optional(U&&) [with U = bool; typename std::enable_if<absl::conjunction<absl::negation<std::is_same<absl::in_place_t, typename std::decay<_Func>::type> >, absl::negation<std::is_same<absl::optional<T>, typename std::decay<_Func>::type> >, absl::negation<std::is_convertible<U&&, T> >, std::is_constructible<T, U&&> >::value, bool>::type <anonymous> = false; T = std::vector<bool>]’
  392 |     https_record_compatibility_ = {true};
      |                                        ^
```